package cn.lovingliu.mapper;

import cn.lovingliu.pojo.Equipment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int insert(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int insertSelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    Equipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int updateByPrimaryKeySelective(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int updateByPrimaryKey(Equipment record);

    /**
     * 预减库存
     * @param equipmentId
     * @param borrowCount
     * @return
     */
    int decreaseCount(@Param("equipmentId") Integer equipmentId, @Param("borrowCount") Integer borrowCount);

    int increaseCount(@Param("equipmentId") Integer equipmentId,@Param("increaseCount") Integer increaseCount);

    List<Equipment> selectListByStatus(Integer status);
}