package cn.lovingliu.mapper;

import cn.lovingliu.pojo.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    int updateByPrimaryKey(User record);

    User selectByTelephone(String telephone);

    List<User> selectByType(Integer userType);

    int increaseInfractionsCount(Integer id);
    int decreaseInfractionsCount(Integer id);
}