package cn.lovingliu.pojo;

import java.io.Serializable;
import java.util.Date;

public class Equipment implements Serializable {
    private Integer id;

    private String portrait;

    private String name;

    private String introduction;

    private Integer amount;

    private Integer status;

    private String damageDescription;

    private Date createdTime;

    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.id
     *
     * @return the value of em_equipment.id
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.id
     *
     * @param id the value for em_equipment.id
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.portrait
     *
     * @return the value of em_equipment.portrait
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.portrait
     *
     * @param portrait the value for em_equipment.portrait
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.name
     *
     * @return the value of em_equipment.name
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.name
     *
     * @param name the value for em_equipment.name
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.introduction
     *
     * @return the value of em_equipment.introduction
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.introduction
     *
     * @param introduction the value for em_equipment.introduction
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.amount
     *
     * @return the value of em_equipment.amount
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.amount
     *
     * @param amount the value for em_equipment.amount
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.status
     *
     * @return the value of em_equipment.status
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.status
     *
     * @param status the value for em_equipment.status
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.damage_description
     *
     * @return the value of em_equipment.damage_description
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public String getDamageDescription() {
        return damageDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.damage_description
     *
     * @param damageDescription the value for em_equipment.damage_description
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setDamageDescription(String damageDescription) {
        this.damageDescription = damageDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.created_time
     *
     * @return the value of em_equipment.created_time
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.created_time
     *
     * @param createdTime the value for em_equipment.created_time
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_equipment.updated_time
     *
     * @return the value of em_equipment.updated_time
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_equipment.updated_time
     *
     * @param updatedTime the value for em_equipment.updated_time
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_equipment
     *
     * @mbg.generated Sun Mar 08 16:51:11 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", portrait=").append(portrait);
        sb.append(", name=").append(name);
        sb.append(", introduction=").append(introduction);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", damageDescription=").append(damageDescription);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}