package cn.lovingliu.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    private Integer id;

    private String number;

    private String name;

    private Integer gender;

    private Integer type;

    private String telephone;

    private String password;

    private String college;

    private String major;

    private Integer infractionsCount;

    private Integer inBlacklist;

    private Date createdTime;

    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.id
     *
     * @return the value of em_user.id
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.id
     *
     * @param id the value for em_user.id
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.number
     *
     * @return the value of em_user.number
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.number
     *
     * @param number the value for em_user.number
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.name
     *
     * @return the value of em_user.name
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.name
     *
     * @param name the value for em_user.name
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.gender
     *
     * @return the value of em_user.gender
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.gender
     *
     * @param gender the value for em_user.gender
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.type
     *
     * @return the value of em_user.type
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.type
     *
     * @param type the value for em_user.type
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.telephone
     *
     * @return the value of em_user.telephone
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.telephone
     *
     * @param telephone the value for em_user.telephone
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.password
     *
     * @return the value of em_user.password
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.password
     *
     * @param password the value for em_user.password
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.college
     *
     * @return the value of em_user.college
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.college
     *
     * @param college the value for em_user.college
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setCollege(String college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.major
     *
     * @return the value of em_user.major
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.major
     *
     * @param major the value for em_user.major
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.infractions_count
     *
     * @return the value of em_user.infractions_count
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Integer getInfractionsCount() {
        return infractionsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.infractions_count
     *
     * @param infractionsCount the value for em_user.infractions_count
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setInfractionsCount(Integer infractionsCount) {
        this.infractionsCount = infractionsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.in_blacklist
     *
     * @return the value of em_user.in_blacklist
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Integer getInBlacklist() {
        return inBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.in_blacklist
     *
     * @param inBlacklist the value for em_user.in_blacklist
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setInBlacklist(Integer inBlacklist) {
        this.inBlacklist = inBlacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.created_time
     *
     * @return the value of em_user.created_time
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.created_time
     *
     * @param createdTime the value for em_user.created_time
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_user.updated_time
     *
     * @return the value of em_user.updated_time
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_user.updated_time
     *
     * @param updatedTime the value for em_user.updated_time
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user
     *
     * @mbg.generated Sun Mar 08 13:15:23 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", number=").append(number);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", type=").append(type);
        sb.append(", telephone=").append(telephone);
        sb.append(", password=").append(password);
        sb.append(", college=").append(college);
        sb.append(", major=").append(major);
        sb.append(", infractionsCount=").append(infractionsCount);
        sb.append(", inBlacklist=").append(inBlacklist);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}